name: spotify
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg:
  equatable: ^2.0.5
  hydrated_bloc:
  path_provider:
  firebase_core:
  firebase_auth:
  firebase_storage:
  get_it:
  dartz:
  cloud_firestore:
  just_audio:
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  file_picker: ^8.1.2
  firebase_app_check: ^0.2.1+8
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bunny_studio.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
